<Project Sdk="MSTest.Sdk/4.3.3">

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Web.v8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server\Server.csproj" />
  </ItemGroup>

</Project>
