<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Web.v8" />
    <PackageReference Include="Meziantou.Framework.Http" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="dotNetRdf.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\dotNetRDF.Wrapping\dotNetRDF.Wrapping.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>

</Project>
